spring.application.name=hackathon
server.port=8081
spring.datasource.url=jdbc:sqlite:quiz.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.static-locations=file:../Musics/music_quiz_dataset/audio/
spring.jpa.properties.hibernate.format_sql=true
